### ISSUE TITLE
Use var instead of let in structs where applicable

### ISSUE THREAD

**Issue by ayoy** [chalup/advent-swift#4]
https://github.com/chalup/advent-swift/blob/c1bae58daca34736f7bc68fc2059eae9cf195906/Sources/advent2019/day3.swift#L4

Consider the following:

    struct Point : Hashable {
        let x: Int
        let y: Int
    }

    var p = Point(x: 0, y: 0)
    p.x = 5  // Cannot assign to property: 'x' is a 'let' constant

Even though you created a mutable Point instance `p`, you can't change its fields because they're immutable. Obviously, there are situations when your approach is perfectly valid, but it's not very common. A more common case would be this:

    struct Point : Hashable {
        var x: Int
        var y: Int
    }

    var p = Point(x: 0, y: 0)
    p.x = 5  // 👍 

    let q = Point(x: 1, y: 1)
    p.x = 3 // Cannot assign to property: 'p' is a 'let' constant

Finally, have a look at this:

    class Point : Hashable {
        var x: Int = 0 // provide default values so that the class
        var y: Int = 0 // doesn't require an initializer
    }

    let p = Point()
    p.x = 5  // 👍

**Comment by chalup** [comment]
Ah, I'm coming from the JVM world where everything is a reference type.

I've made the `Point` an immutable data structure, because it's going to be put in a `Set`, and in Java/Kotlin world putting an object into `Set` or using it as a key in a `Map` and mutating it is a big no-no (it violates the invariants of these data structures and you get crap like duplicates in `Set`).

Here, I assume, it's gonna be copied upon adding it to the `Set`, so it can be mutable, right?

And kindof a related question: is using value types in collections acceptable from performance perspective, or should I switch to immutable reference types?

**Comment by ayoy** [comment]
Yes, struct instances will be copied when added to a set.
It's a case-by-case thing with using value types in collections, but it's not discouraged in general. For example it's a normal thing to parse JSON into structs (using `Codable` protocol and `JSONDecoder`/`JSONEncoder`).

I believe that scenarios where you just create a struct instance and immediately add it to a collection are very well optimized by a compiler.
